version: "3.8"

services:
  app:
    image: nextcloud:latest
    container_name: nextcloud-app
    restart: unless-stopped
    ports:
      - ${NEXTCLOUD_PORT:-80}:80
    depends_on:
      - db
    environment:
      VIRTUAL_HOST: "cloud.xpand4b.de"
      LETSENCRYPT_HOST: "cloud.xpand4b.de"
      LETSENCRYPT_EMAIL: "xpand.4beatz@gmail.com"
      NEXTCLOUD_ADMIN_USER: "Admin"
      NEXTCLOUD_ADMIN_PASSWORD: "A179ehkoliwaokh98eh74"
    volumes:
      - nextcloud:/var/www/html
      - ./app/config:/var/www/html/config
      - ./app/custom_apps:/var/www/html/custom_apps
      - ./app/data:/var/www/html/data
      - ./app/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime:ro

  db:
    image: mariadb
    container_name: nextcloud-mariadb
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USER}"
    volumes:
      - db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro

volumes:
  nextcloud:
  db:
