version: "3.8"

services:
  homeassistant:
    image: homeassistant/home-assistant
    container_name: home-assistant
    restart: always
    privileged: true
    network_mode: host
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro