version: "3.8"

services:
  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    restart: unless-stopped
    environment:
      PGID: "${PGID}"
      PUID: "${PUID}"
      TZ: "${TIMEZONE}"
    volumes:
      - ./config:/config
    ports:
      - ${HEIMDALL_PORT:-80}:80