version: "3.8"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp # Only required if you are using Pi-hole as your DHCP server
      - ${PIHOLE_PORT:-80}:80/tcp
      - 443:443/tcp
    environment:
      TZ: "{$TIMEZONE}"
      WEBPASSWORD: "{$WEB_PASSWORD}"
      ADMIN_EMAIL: "{$ADMIN_EMAIL}"
      PIHOLE_DNS_: "{$PIHOLE_DNS}"
    volumes:
      - ./pihole:/etc/pihole
      - ./dnsmasq.d:/etc/dnsmasq.d
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN # Recommended but not required (DHCP needs NET_ADMIN)