version: "3.8"

services:
  app:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: always
    volumes:
      - uptime-kuma:/app/data
    ports:
      - ${UPTIME_KUMA_PORT:-3001}:3001

volumes:
  uptime-kuma:
    driver: local