version: "3.8"

services:
  searxng:
    image: searxng/searxng
    container_name: searxng
    restart: unless-stopped
    ports:
      - ${SEARXNG_PORT:-8080}:8080
    #environment:
      #BASE_URL: http://localhost:$PORT
      #INSTANCE_NAME: my-instance
    volumes:
      - ./data:/etc/searxng
