version: "3.8"

services:
  homer:
    image: b4bz/homer:latest
    container_name: homer
    restart: unless-stopped
    ports:
      - ${HOMER_PORT:-8080}:8080
    environment:
      UID: "${UID}"
      GID: "${UID}"
    volumes:
      - ./assets:/www/assets