version: "3.8"

services:
  code-server:
    image: lscr.io/linuxserver/code-server
    container_name: code-server
    restart: unless-stopped
    environment:
      PGID: "${PGID}"
      PUID: "${PUID}"
      TZ: "${TIMEZONE}"
      PASSWORD: "${PASSWORD}"
      HASHED_PASSWORD: "${HASHED_PASSWORD}"
      SUDO_PASSWORD: "${SUDO_PASSWORD}"
      SUDO_PASSWORD_HASH: "${SUDO_PASSWORD_HASH}"
      PROXY_DOMAIN: "${PROXY_DOMAIN}"
      DEFAULT_WORKSPACE: "${DEFAULT_WORKSPACE}"
    volumes:
      - ./config:/config
    ports:
      - ${CODE_SERVER_PORT:-8443}:8443
